### ISSUE TITLE
token is missing expected \"k8s-aws-v1.\"

### ISSUE THREAD

**Issue by snoby** [heptio/authenticator#83]
I have the heptio-authenticator-aws running in my cluster and at one time I was able to authenticate through it. On my workstation I updated my heptio-authenticator-aws binary ( for the new kubectl executable method of authenticating.  

Following the instructions documented in the root readme file of the repository, I setup my kubeconfig and I'm continually asked for my Username and password.  No logs seem to be coming out of the  server daemon set at this time:

```
kubectl --kubeconfig /Users/snoby/.kube/east-prod_authenticator -n prod get pods
Please enter Username: kubernetes-admin
Please enter Password:
Please enter Username: ^C
```

Version of kubectl:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
The kubeconfig looks like this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJsnipp
    server: https://proxy.api.east-prod.k8s.tro.com
  name: east-prod.k8s.tro.com
contexts:
- context:
    cluster: east-prod.k8s.tro.com
    user: east-prod.k8s.tro.com
  name: east-prod.k8s.tro.com
current-context: east-prod.k8s.tro.com
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "east-prod.k8s.tro.com"
```
I have verified that I can authenticate to AWS  using the aws cli tools

Also when I run the tool in the `old` fashion way of authenticating to the cluster ( meaning it's part of the command line, the server logs indicate  
```
[heptio-authenticator-aws-kt2nc][heptio-authenticator-aws]  | time="2018-05-15T21:32:26Z" level=warning msg="access denied" client="127.0.0.1:13432" error="token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
[heptio-authenticator-aws-kt2nc][heptio-authenticator-aws]  | time="2018-05-15T21:32:27Z" level=warning msg="access denied" client="127.0.0.1:13432" error="token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
[heptio-authenticator-aws-kt2nc][heptio-authenticator-aws]  | time="2018-05-15T21:32:27Z" level=warning msg="access denied" client="127.0.0.1:13432" error="token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
[heptio-authenticator-aws-kt2nc][heptio-authenticator-aws]  | time="2018-05-15T21:32:27Z" level=warning msg="access denied" client="127.0.0.1:13432" error="token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
```

When I look at the token generated it looks like this:
```
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"token":"k8s-aws-v1.aHR0cHM6Ly9zdHMuYW1hsnippet"}}
```
So i'm guessing this version ( I couldn't find a version field) is not compatible with the old way of authenticating?
