### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by tomweston** [heptio/authenticator#92]
## EKS Cluster Authentication

**TLDR;** Not sure what I'm missing here 😢 ??

```
error: You must be logged in to the server (Unauthorized)
```
## Steps Taken:

- **1. EKS Cluster created in AWS Console**

- **2. IAM Role created with the following steps:**

[https://github.com/heptio/authenticator#1-create-an-iam-role](https://github.com/heptio/authenticator#1-create-an-iam-role)

- **3. STS Assume role allowed on Role from user account in AWS_PROFILE**

```
{
    "Sid": "KubernetesAdmin",
    "Effect": "Allow",
    "Action": "sts:AssumeRole",
    "Resource": "arn:aws:iam::012345678910:role/KubernetesAdmin"
}
```
- **4. Values from UI copied and placed into a new config ~/.kube/config-clustername as per AWS Documentation:**

[https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html)

```
apiVersion: v1
clusters:
- cluster:
    server: <APIServerEndpointURL>
    certificate-authority-data: <CAbase64blob>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "clustername"
        - "-r"
        - "arn:aws:iam::012345678910:role/KubernetesAdmin"
```

- **5. Kubectl get nodes using new config:**

```
$ kubectl --kubeconfig ~/.kube/config-clustername get nodes
error: You must be logged in to the server (Unauthorized)

```
😢 What's missing?
