### ISSUE TITLE
Allow profiles to be specified

### ISSUE THREAD

**Issue by asobrien** [heptio/authenticator#94]
It would be nice if the AWS profile that credentials should be sourced from could be
specified when using `heptio-authenticator-aws`. Of course, this can already be done
by using the `AWS_PROFILE` environment variable. However, adding profiles as an
explicit option would be useful when working with clusters across multiple AWS
accounts and allow seamless switching.

For example, if a `--profile` flag was supported then `kubectl` would not require the
`AWS_PROFILE` environment variable to be modified for each cluster/account. The
appropriate profile could be specified directly in the kubeconfig file, e.g.:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: ${server}
    certificate-authority-data: ${cert}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "mycluster"
        - "-p"
        - "dev"
```

**Comment by christopherhein** [comment]
Hey @asobrien there is actually support for this built into the `ExecCredentials` flow… 

Update your config to include:

```yaml
env:
- name: AWS_PROFILE
   value: dev
```

more information - https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins#configuration

For the PR you submitted maybe we can make that to add documentation to how to configure this instead of adding the flag?
